# NEDEN PY

In [4]:
import numpy as np

In [5]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [6]:
a=np.array([1,2,3,4,5])

In [7]:
type(a)

numpy.ndarray

In [8]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [12]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [13]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [14]:
np.random.normal(10,4,(3,4))

array([[ 7.43313475,  9.45435195, 10.82426538, 13.36776966],
       [ 6.8606134 ,  8.61550174, 16.4243254 ,  8.59978029],
       [11.79035123, 10.86126585, 14.90044267, 10.83833115]])

In [15]:
np.random.randint(0,10,(3,4))

array([[7, 0, 1, 3],
       [9, 6, 4, 1],
       [6, 2, 4, 8]])