In [7]:
import numpy as np

In [8]:
a=np.random.randint(10,size=(5,5))

In [9]:
a[0][0]=99

In [10]:
a

array([[99,  9,  9,  8,  9],
       [ 3,  3,  5,  0,  7],
       [ 6,  0,  1,  0,  9],
       [ 0,  6,  1,  7,  8],
       [ 6,  3,  2,  6,  5]])

In [1]:
import numpy as np

In [2]:
v=np.array([1,2,3,4,5])

In [3]:
v>5

array([False, False, False, False, False])

In [4]:
v[v<3]

array([1, 2])

In [5]:
v[v!=3]

array([1, 2, 4, 5])

In [6]:
v*2

array([ 2,  4,  6,  8, 10])

In [7]:
v/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [ ]:
# matematiksel işlemler

In [8]:
?np


Type:        module
String form: <module 'numpy' from '/home/deniz/.local/lib/python3.6/site-packages/numpy/__init__.py'>
File:        ~/.local/lib/python3.6/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x 

In [ ]:
# np.divide(v,4)  multiply  mod  substract hepsi  absolute(np.array([-3]))  3  np.sin(360)

In [14]:
nuöp