In [9]:
import numpy as np

In [10]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## birlestirme concentation

In [12]:
x=np.array([1,2,3])

In [13]:
y=np.array([4,5,6])

In [14]:
np.concatenate( [x,y])

array([1, 2, 3, 4, 5, 6])

### array ayırma

In [24]:
import numpy as np

In [25]:
x=np.array([0,1,2,3,4,5,6,7,8,9])

In [26]:
np.split(x,[3,5])

[array([0, 1, 2]), array([3, 4]), array([5, 6, 7, 8, 9])]

In [27]:
a,b,c =np.split(x,[3,5])

In [28]:
a

array([0, 1, 2])

In [29]:
#iki boyutlu ayırma  (vsplit vektör ayırmal)

In [30]:
m=np.arange(16).reshape(4,4)


In [ ]:
m

In [31]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [32]:
ust,alt=np.split(m,[2])

In [33]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [34]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
#np.sort(sıralama)